config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'static_pages#about'
  get 'further_actions' => 'questions#further_actions'
  get 'calculate' => 'questions#input'
  post 'api' => 'questions#api'
  get 'howto' => 'static_pages#howto'
  get 'need' => 'static_pages#need'
  post 'compute' => 'questions#compute'
  resources :questions

  root 'home#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def input
  end

  def further_actions
  end
  
  def compute
    diameter = params[:input][:diameter]

    if( diameter.to_i > 0 ) 
      rate_1 = 7.5
      rate_2 = 15.0
      rate_3 = 30.0

      @value_1 = ( rate_1 * 3.14 ) * ( ( diameter.to_f / 200.0 ) ** 2 )
      @value_2 = ( rate_2 * 3.14 ) * ( ( diameter.to_f / 200.0 ) ** 2 )
      @value_3 = ( rate_3 * 3.14 ) * ( ( diameter.to_f / 200.0 ) ** 2 )
    else
      flash.now[:error] = "Invalid Input"
      render 'home/home'
    end
  end

  def api
    diameter = params[:diameter]
    if( diameter.to_i != 0 ) 
      some_data = {'message' => diameter }
      render :json => some_data
    else
      render :json => { 'message' => 'Error' }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def need
  end

  def howto
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/home.html.erb
<div class="container">

  <div class="panel">
    <div class="panel-body">
      <div class="col-md-10 col-md-offset-1">
        <%= render 'questions/form' %>
      </div>
    </div>
  </div>


  <div class="panel">
    <div class="panel-body">
      <div class="col-md-5 ">
      <%= image_tag("philippine-flag.jpg")%>
      </div>

      <div class="col-md-6 col-md-offset-1">
        <h1>
            Bantay Batya.
        </h1>
        <p> 
          Sa panahon ngayon, maraming kagamitan na ang na-imbento upang makapaghanda sa mga delubyo dulot ng kalikasan. Isa na rito ang ‘rain gauge’ na tumantansiya ng tubig ulan. Subalit, naging malaking suliranin ang pamamahagi nito sa mga lokal na komunidad sa liblib na bahagi ng bansa. Nais ng sangguning ito makagawa ng mga makabagong kagamitan gamit lamang ang araw-araw na kasangkapan—ang planggana.
        </p>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |type, message| %>
    <div class="alert alert-dismissable alert-<%= type == "error" ? 'danger' : 'success' %> fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'How-To', need_path %></li>
        <li><%= link_to 'Further Actions', further_actions_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
    
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BantayBatya</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for :input, url: compute_path do |f| %>
  <fieldset>
    <legend>Calculate Volumes</legend>
    <div class="form-group">
      <label for="inputEmail" class="col-lg-2 control-label">Diameter: </label>
      <div class="col-lg-10">
        <%= f.text_field :diameter, class: "form-control", value: "", placeholder: "Input diameter" %><br/>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button class="btn btn-default">Cancel</button>
        <button type="submit" id="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
<% end %>

<script>
//   $(function() {
//     $("#submit").click(function() {
//       var diameter = $('#input[diameter]');
//       console.log(diameter);
//       $.ajax({
//         diameter: 'diameter',
//         url: '/api',
//         type: 'POST',
//         data: {diameter: diameter.val()},
//         dataType: 'json',
//         success: function(data) {
//           alert(data);
//         }
//         error: function(e, data) {
//           alert(e, data);
//         }
//       });
//     });
//   });
// </script>

app/views/questions/compute.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">Results</div>
    <div class="panel-body">
      <%= @value_1 %> L from water level ("Mag-ingat")<br/>
      <%= @value_2 %> L from water level ("Mag-handa)<br/>
      <%= @value_3 %> L from water level ("Bakwat")<br/>
    </div>
  </div>
  <%= link_to 'Back', root_path, class: 'btn btn-lg btn-default' %>
</div>

app/views/questions/further_actions.html.erb
<h1>Further Actions</h1>
<h1>Change me at views/questions/further_actions.html.erb</h1>

app/views/questions/input.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-body">
    <div class="container">
      <%= render 'questions/form' %>
    </div>
    <%= link_to 'How To', need_path %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>About</h1>
<h1>Change me at views/static_pages/about.html.erb</h1>

app/views/static_pages/howto.html.erb
<div class="jumbotron">
  <h1> Paano gumawa ng "improvised" Rain Gauge</h1>
  <p>
    <li>1) I-compute ang mga "grid" o linya sa iyong batya. Kasama rito ang  "tubig level" , "mang-ingat" , "mag-handa" at "bakwet"</li>
    <%= image_tag 'final.jpg' %>
    <li>2) Kapag maliit lang ang batya , maaring lagyan ito ng bato at 2 litro ng tubig  upang hindi ito tangayin ng hangin. Sukatin ang volume na nabigay ng mga bato at 2 litro ng tubig. Ito ang "tubig-level" o "zero mark" natin</li>
    <%= image_tag '2nd.jpg' %>
    <li>3) Magsukat ng volume tubig ayon sa na-compute</li>
    <%= image_tag 'tubig.jpg' %>
    <li>4) Idagdag ito sa batya , pagkatapos markahan ang batya , ulitin ito hangang magkaroon ng "mag-ingat", "mag-handa" at "bakwet" na linya ang batysa</li>
    <li>5) Iiwan ito sa labas ng bahay ng isang oras habang umuulan.</li>
    <li>6) Kunin ang batya at ikumapra sa mga linya ng batya.</li>
  </p>
</div>

app/views/static_pages/need.html.erb
<div class="jumbotron">
  <h1> What you need to make your own improvised Rain Gauge </h1>
  <p>
    <li>1) Planggana (no specific size), basta walang butas</li>
    <li>2) Plastic ruler with centimeters (best) or tapemeasure for measuring distances.</li>
    <li>3) A measuring cup (has liters or metric measure).</li>
    <li>4) Indelible marker.</li>
    <li>5) Optional: stones, to weigh down the basin.</li>
  </p>
<%= link_to 'How to create your own Rain Gauge', howto_path %><br/>
<%= link_to 'Calculate', calculate_path %><br/>
<%= link_to 'Further Actions', further_actions_path %>
</div>